export const FRIEND_GET_REQUEST = 'FRIEND_GET_REQUEST';
export const FRIEND_GET_SUCCESS = 'FRIEND_GET_SUCCESS';
export const FRIEND_GET_FAIL = 'FRIEND_GET_FAIL';
export const FRIEND_GET_RESET = 'FRIEND_GET_RESET';